void test_vector();
void test_set1();
void test_set2();
void test_set3();
void test_iota();
void test_for_each();
void test_binary_search();
void test_map();
void test_find();
void test_search();
void test_return();
// test_reverse_and_count.h
void test_reverse();
void test_count();
// test_for_each_parallel.h
void test_for_each_parallel();
// test_copy_if.h
void test_copy_if();